---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefiles-nfs-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  storageClassName: azurefiles-nfs-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: file.csi.azure.com
    volumeHandle: nfsvhhfhet#nfs
    volumeAttributes:
      protocol: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefiles-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefiles-nfs-sc
  resources:
    requests:
      storage: 100Gi
