---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefiles-nfs-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  storageClassName: azurefiles-nfs-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: file.csi.azure.com
    volumeHandle: nfsvhhfhet#nfs
    volumeAttributes:
      protocol: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefiles-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefiles-nfs-sc
  resources:
    requests:
      storage: 100Gi
---
# --- Secret: RStudio Configuration -------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: rstudio-config
type: Opaque
stringData:
  admin_secret: "admin-ad-credentials" 
  domain_fqdn: "rstudio.mikecloud.com"
  vault_name: "ad-key-vault-2dwh3diu"
  netbios: "RSTUDIO"

# Notes:
# - The values here are low sensitivity; credentials are stored in AWS Secrets Manager.
# - Mounted as text files inside the container (not environment variables).
---