# ==============================================================================
# StorageClass for Azure Files (NFS protocol)
# ==============================================================================
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefiles-nfs-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: file.csi.azure.com
parameters:
  skuName: Standard_LRS       # Or Premium_LRS for higher performance
  protocol: nfs               # Ensures NFS mode instead of SMB
mountOptions:
  - vers=4.1
  - nconnect=8
  - hard
  - timeo=600
  - retrans=2
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true

---
# ==============================================================================
# Static PersistentVolume - Binds to Existing Azure Files NFS Share
# ==============================================================================
apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefiles-nfs-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefiles-nfs-sc
  csi:
    driver: file.csi.azure.com
    volumeHandle: "rstudio-servers-rg#nfsvhhfet#nfs"  # ← REQUIRED FORMAT: {rg}#{account}#{share}
    volumeAttributes:
      shareName: nfs
      protocol: nfs  
---
# ==============================================================================
# PersistentVolumeClaim - Binds to PV
# ==============================================================================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefiles-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefiles-nfs-sc
  resources:
    requests:
      storage: 100Gi
---
# --- Secret: RStudio Configuration -------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: rstudio-config
type: Opaque
stringData:
  admin_secret: "admin-ad-credentials" 
  domain_fqdn: "rstudio.mikecloud.com"
  vault_name: "ad-key-vault-2dwh3diu"
  netbios: "RSTUDIO"

# Notes:
# - The values here are low sensitivity; credentials are stored in an Azure Key Vault.
# - Mounted as text files inside the container (not environment variables).
---
# --- Headless Service for StatefulSet ----------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: rstudio
  labels:
    app: rstudio
spec:
  clusterIP: None
  selector:
    app: rstudio
  ports:
    - port: 8787
      name: rstudio
# Notes:
# - Enables unique, stable hostnames like rstudio-0.rstudio.<namespace>.svc.
# - Required for StatefulSet hostname resolution and AD compatibility.
---
# ==============================================================================
# StatefulSet for RStudio Server Cluster on Azure AKS
# ==============================================================================
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rstudio
  labels:
    app: rstudio
spec:
  serviceName: "rstudio"
  replicas: 1
  selector:
    matchLabels:
      app: rstudio
  template:
    metadata:
      labels:
        app: rstudio
    spec:
      # ------------------------------------------------------------------------
      # Security Context for NFS Permissions
      # ------------------------------------------------------------------------
      securityContext:
        fsGroup: 10001
        runAsUser: 10001
        runAsGroup: 10001

      # ------------------------------------------------------------------------
      # Service Account (optional)
      # ------------------------------------------------------------------------
      serviceAccountName: keyvault-access-sa

      # ------------------------------------------------------------------------
      # Container Specification
      # ------------------------------------------------------------------------
      containers:
      - name: rstudio
        image: rstudioozx6dp34.azurecr.io/rstudio:rstudio-server-rc1
        ports:
        - containerPort: 8787

        # ----------------------------------------------------------------------
        # Resource Requests & Limits
        # ----------------------------------------------------------------------
        resources:
          requests:
            cpu: "800m"
            memory: "2000Mi"
          limits:
            cpu: "2000m"
            memory: "3500Mi"

        # ----------------------------------------------------------------------
        # Health Probes (RStudio Sign-in Endpoint)
        # ----------------------------------------------------------------------
        readinessProbe:
          httpGet:
            path: /auth-sign-in
            port: 8787
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6

        livenessProbe:
          httpGet:
            path: /auth-sign-in
            port: 8787
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3

        # ----------------------------------------------------------------------
        # Secret Volume Mount (Configuration)
        # ----------------------------------------------------------------------
        volumeMounts:
        - name: rstudio-config-vol
          mountPath: /etc/rstudio-config
          readOnly: true

        # ----------------------------------------------------------------------
        # Azure Files NFS Volume Mounts
        # ----------------------------------------------------------------------
        - name: azurefiles-nfs-storage
          mountPath: /nfs
        - name: azurefiles-nfs-storage
          mountPath: /home
          subPath: home

      # ------------------------------------------------------------------------
      # Volumes (Secret + Azure Files PVC)
      # ------------------------------------------------------------------------
      volumes:
        - name: rstudio-config-vol
          secret:
            secretName: rstudio-config
        - name: azurefiles-nfs-storage
          persistentVolumeClaim:
            claimName: azurefiles-nfs-pvc
---
# --- ClusterIP Service for External Access -------------------------------
apiVersion: v1
kind: Service
metadata:
  name: rstudio-external
  labels:
    app: rstudio
spec:
  selector:
    app: rstudio
  ports:
    - port: 8787
      targetPort: 8787
      name: rstudio
---
# ==============================================================================
# Ingress Resource for RStudio Server (HTTP Load Balancer with Stickiness)
# ==============================================================================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rstudio-ingress
  annotations:
    # --- Enable Sticky Sessions ----------------------------------------------
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "rstudio_session"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/session-cookie-path: "/"

    # --- Backend Protocol (HTTP) ---------------------------------------------
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rstudio-external
                port:
                  number: 8787

